# causal_discovery.sub

executable = causal_discovery.sh
arguments  = $(run_index) $(run_name) $(data_path) $(alpha) $(sample_size) $(depth)

container_image = docker://kayvansinha/causal-env:latest

transfer_input_files = causal_discovery_fisherz.py,$(data_path)

log    = logs/$(run_name).log
output = logs/$(run_name).out
error  = logs/$(run_name).err

transfer_output_files = $(run_name).pkl, $(run_name).png

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus   = 1
request_memory = 16GB
retry_request_memory = RequestMemory*2
request_disk   = 5GB

queue run_index, run_name, data_path, alpha, sample_size, depth from runs_v2.txt